spring.application.name=E-commerce_Backoffice

# [DB Info]
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# [JPA/Hibernate Config]
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:index.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.continue-on-error=true

# [Formatting]
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# [JWT Config]
jwt.secret.key=${JWT_SECRET_KEY}

# [security log]
logging.level.org.springframework.security=DEBUG

spring.profiles.active=local
